version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: >
      sh -c "yarn run start"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET='super-secret-jwt-key'
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "4000:5432"
